{
 "title": "DevOps",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "environment", "query": "dev : 0, homolog : 1, prod : 2" }
  ]
 },
 "panels": [
  {
   "title": "Total Deploys By Week",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  to_char(deploy_creation_datetime, 'IYYY-IW') AS \"metric\",\n  COUNT(*) AS \"value\"\nFROM deploys\nWHERE deploy_env=$environment\nGROUP BY \"metric\"\nORDER BY \"metric\" DESC"
    }
   ]
  },
  {
   "title": "Percentage of Deploys with Issue By Week",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  to_char(deploy_creation_datetime, 'IYYY-IW') AS \"metric\",\n  (cast(COUNT(CASE WHEN deploy_caused_issue IS TRUE THEN 1 END) as float)*100.0)/cast(COUNT(*) as float) AS \"value\"\nFROM deploys\nWHERE deploy_env=$environment\nGROUP BY \"metric\"\nORDER BY \"metric\" DESC"
    }
   ]
  },
  {
   "title": "Top Failing Deploy Percentages",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  deploy_repository as \"metric\",\n  (cast(COUNT(CASE WHEN deploy_caused_issue IS TRUE THEN 1 END) as float)*100.0)/cast(COUNT(*) as float) AS \"value\"\nFROM deploys\nWHERE deploy_env=$environment AND deploy_repository!='test'\nGROUP BY \"metric\"\nORDER BY \"value\" DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "15 Last Deploys",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  deploy_creation_datetime AS \"Deploy Time\",\n  deploy_caused_issue AS \"Caused Issue\",\n  deploy_repository AS \"Service\",\n  deploy_responsible as \"Responsible\"\nFROM deploys\nWHERE deploy_env=$environment\nORDER BY \"deploy_creation_datetime\" DESC\nLIMIT 15"
    }
   ]
  },
  {
   "title": "15 Last Deploys With Issue",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  deploy_creation_datetime AS \"Deploy Time\",\n  deploy_repository AS \"Service\"\nFROM deploys\nWHERE deploy_env=$environment AND deploy_caused_issue IS TRUE\nORDER BY \"deploy_creation_datetime\" DESC\nLIMIT 15"
    }
   ]
  }
 ]
}